apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: test-app:/Deployment:default/testapp1-deployment
  labels:
    app: testapp1
  name: testapp1-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp1
  template:
    metadata:
      labels:
        app: testapp1
    spec:
      containers:
        - image: nginx:1.14.2
          name: testapp1
          ports:
            - containerPort: 80
